name: Build Frontend

on:
  workflow_call:
    inputs:
      target_branch:
        required: true
        type: string
      build_branch:
        required: true
        type: string

jobs:
  build_frontend:
    name: Build and unit test frontend
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.build_branch }}

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: "14"
          cache: yarn
          cache-dependency-path: frontend/yarn.lock

      - name: Build
        run: make clean-all build-ui

      - name: Test frontend
        run: |
          cd frontend
          yarn pretty-quick --check --verbose --branch ${{ inputs.target_branch }}
          yarn test

      - name: Upload frontend build
        uses: actions/upload-artifact@v3
        with:
          name: build
          path: frontend/build/
